defaults:
  - _self_
  - dataset: default
  - model: default
  - training: default

project:
  name: "Music_MMLS"
  seed: 42
  device: "cuda"

  wandb_entity: "sasha_kovylyaev-hse"
  experiment_name: "default"
  wandb:
    api_key: ${env:WANDB_API_KEY}
    project: ${project.name}
    entity: ${project.wandb_entity}
    name: ${project.experiment_name}
